# Generated by Django 4.2.1 on 2023-06-12 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0020_alter_authorizeusers_manage_company_stock_or_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsoldincash',
            name='date_product_sold',
            field=models.DateTimeField(default=datetime.date(2023, 6, 12)),
        ),
    ]
