# Generated by Django 4.2.1 on 2023-07-19 08:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeApp', '0021_alter_productsoldincash_date_product_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_full_name', models.CharField(max_length=1000)),
                ('customer_phone_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'List of Customers',
            },
        ),
        migrations.CreateModel(
            name='ShopBrandMainLogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('brand_image', models.ImageField(upload_to='media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Company logo/  brand',
            },
        ),
        migrations.RemoveField(
            model_name='customersorders',
            name='customer_Full_name',
        ),
        migrations.RemoveField(
            model_name='customersorders',
            name='customer_phone_number',
        ),
        migrations.AddField(
            model_name='productsoldincash',
            name='date_for_issues_invoice',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='productsoldincash',
            name='date_product_sold',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productsoldincash',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customersorders',
            name='custoomer_full_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeApp.customerdetails'),
        ),
        migrations.AddField(
            model_name='productsoldincash',
            name='customer_full_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storeApp.customerdetails'),
        ),
    ]
